import Head from 'next/head'

export const Header = () => {
  return (
    <Head>
      <title>携手未来</title>
      <meta name="description" content="Generated by create next app"/>
      <link rel="icon" href="/favicon.ico"/>
    </Head>
  )
}

export default Header
