/**
 * Copyright (c) Hand-Future @2023. and its affiliates.
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
*/

import Head from 'next/head'

export const Header = () => (
  <Head>
    <title>携手未来</title>
    <meta name="description" content="Generated by create next app"/>
    <link rel="icon" href="/public/favicon.ico"/>
  </Head>
)

export default Header
